{
 "title": "Docker Health",
 "description": "Metricas dos dockers.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Usage do cpu (%) total, dos dockers ativos.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\", id=~\"/system.slice/docker-.*\\\\.scope\"}[30s])) * 100 > 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Individual Docker CPU Usage",
   "type": "bargauge",
   "description": "Percentagem de CPU utilizada por cada container.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  rate(container_cpu_usage_seconds_total{cpu=\"total\", id=~\"/system.slice/docker-.*\\\\.scope\"}[30s]),\n  \"short_id\",\n  \"$1\",\n  \"id\",\n  \".*/(docker-.*)\\\\.scope\"\n) * 100 > 0",
     "legendFormat": "{{short_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Usage de memoria(%) total, dos dockers ativos. (5m inbetween docker statup for accurate readings)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_usage_bytes{id=~\"/system.slice/docker-.*\\\\.scope\"}\n  - container_memory_cache{id=~\"/system.slice/docker-.*\\\\.scope\"}\n) / (1024*1024) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Individual Docker Memory Usage",
   "type": "bargauge",
   "description": "Mbs a serem utilizados por cada container. (5m inbetween docker statup for accurate readings)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    container_memory_usage_bytes{id=~\"/system.slice/docker-.*\\\\.scope\"}\n    -\n    container_memory_cache{id=~\"/system.slice/docker-.*\\\\.scope\"}\n  ) > 0,\n  \"short_id\",\n  \"$1\",\n  \"id\",\n  \".*/(docker-.*)\\\\.scope\"\n) / (1024*1024) > 0\n",
     "legendFormat": "{{short_id}}"
    }
   ]
  },
  {
   "title": "Alert List - CPU",
   "type": "alertlist",
   "description": "Lista de alertas para verificar a saude dos dockers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 }
  },
  {
   "title": "Alert List - Memory",
   "type": "alertlist",
   "description": "Lista de alertas para verificar a saude dos dockers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 }
  }
 ]
}