{
 "title": "Serviço Notifications",
 "description": "Informações sobre o estado do serviço de GW.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lâtencia do Notifications",
   "type": "timeseries",
   "description": "Valores da lâtencia do serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_notifications_hist_sum{job=\"notifications_service\"}[$__rate_interval])) / (sum(rate(request_latency_seconds_notifications_hist_count{job=\"notifications_service\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de requests",
   "type": "timeseries",
   "description": "Número de requests no serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path) (increase(flask_http_request_duration_seconds_count{path=\"/notifications/send_verification\"}[$__rate_interval])) / 1.2",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by (path) (increase(flask_http_request_duration_seconds_count{path=\"/notifications/order_created\"}[$__rate_interval])) / 1.2",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by (path) (increase(flask_http_request_duration_seconds_count{path=\"/notifications/status\"}[$__rate_interval])) / 1.2",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(\n  increase(flask_http_request_duration_seconds_count{path=~\"/notifications/me\"}[$__rate_interval])\n) by (path) / 1.2",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Notifications (Emails)",
   "type": "table",
   "description": "Todos os pedidos processados iram mandar notifications via email. Estes logs são desse serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"notifications_service\"} |~ `\\[EMAIL ENVIADO\\]|4[0-9][0-9]|5[0-9][0-9]`"
    }
   ]
  },
  {
   "title": "Erros de metodos",
   "type": "table",
   "description": "Todos os logs de erros ao tentar aceder o nosso serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"notifications_service\"} |~ ` 4[0-9][0-9] | 5[0-9][0-9] `"
    }
   ]
  },
  {
   "title": "Logs do serviço",
   "type": "table",
   "description": "Logs do serviço GW, dos metodos importantes.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"notifications_service\"} |= `GET` or `POST`"
    }
   ]
  }
 ]
}