{
 "title": "Serviço Gateway",
 "description": "Informações sobre o estado do serviço de GW.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lâtencia do GW",
   "type": "timeseries",
   "description": "Valores da lâtencia do serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_gateway_hist_sum{instance=\"gw_service:5863\"}[$__rate_interval])) / (sum(rate(request_latency_seconds_gateway_hist_count{instance=\"gw_service:5863\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de requests",
   "type": "timeseries",
   "description": "Número de requests no serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  increase(flask_http_request_duration_seconds_count{path=\"/\"}[$__rate_interval])\n) by (path)",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum by(path) (increase(flask_http_request_duration_seconds_count{path=\"/signup\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum(\n  increase(flask_http_request_duration_seconds_count{path=\"/signup/confirm\"}[$__rate_interval])\n) by (path)\n",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (increase(flask_http_request_duration_seconds_count{path=\"/login\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (increase(flask_http_request_duration_seconds_count{path=\"/logout\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Logs do serviço",
   "type": "table",
   "description": "Logs do serviço GW, dos metodos importantes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"gw_service\"} |= `GET` or `POST`"
    }
   ]
  },
  {
   "title": "Erros de metodos",
   "type": "table",
   "description": "Todos os logs de erros ao tentar aceder o nosso serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"gw_service\"} |~ \" 4[0-9][0-9] | 5[0-9][0-9] \""
    }
   ]
  }
 ]
}