{
 "title": "Serviço Payments",
 "description": "Informações sobre o estado do serviço de GW.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lâtencia do Payments",
   "type": "timeseries",
   "description": "Valores da lâtencia do serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_payments_hist_sum{job=\"payments_service\"}[5m])) / (sum(rate(request_latency_seconds_payments_hist_count{job=\"payments_service\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de requests",
   "type": "timeseries",
   "description": "Número de requests no serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path) (increase(flask_http_request_duration_seconds_count{path=\"/payments\"}[$__rate_interval])) / 2",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "increase(\n  flask_http_request_duration_seconds_count{\n    path=~\"/payments/.+\",\n    path!=\"/payments/me\"\n  }[$__rate_interval]\n)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Logs do serviço",
   "type": "table",
   "description": "Logs do serviço GW, dos metodos importantes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"payments_service\"} |= `GET` or `POST`"
    }
   ]
  },
  {
   "title": "Erros de metodos",
   "type": "table",
   "description": "Todos os logs de erros ao tentar aceder o nosso serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"payments_service\"} |~ ` 4[0-9][0-9] | 5[0-9][0-9] `"
    }
   ]
  }
 ]
}