{
 "title": "Serviço Notifications",
 "description": "Informações sobre o estado do serviço de GW.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lâtencia do Notifications",
   "type": "timeseries",
   "description": "Valores da lâtencia do serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_notifications_hist_sum{job=\"notifications_service\"}[5m])) / (sum(rate(request_latency_seconds_notifications_hist_count{job=\"notifications_service\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de requests",
   "type": "timeseries",
   "description": "Número de requests no serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path) (increase(flask_http_request_duration_seconds_count{path=\"/notifications/send_verification\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum by (path) (increase(flask_http_request_duration_seconds_count{path=\"/notifications/order_created\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum by (path) (increase(flask_http_request_duration_seconds_count{path=\"/notifications/status\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "increase(\n  flask_http_request_duration_seconds_count{\n    path=~\"/notifications/.+\",\n    path!=\"/notifications/me\",\n    path!=\"/notifications/send_verification\",\n    path!=\"/notifications/status\",\n    path!=\"/notifications/order_created\"\n  }[$__rate_interval]\n)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Logs do serviço",
   "type": "table",
   "description": "Logs do serviço GW, dos metodos importantes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"notifications_service\"} |= `GET` or `POST`"
    }
   ]
  },
  {
   "title": "Erros de metodos",
   "type": "table",
   "description": "Todos os logs de erros ao tentar aceder o nosso serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"notifications_service\"} |~ ` 4[0-9][0-9] | 5[0-9][0-9] `"
    }
   ]
  }
 ]
}