{
 "title": "Serviço Orders",
 "description": "Informações sobre o estado do serviço de GW.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lâtencia do Orders",
   "type": "timeseries",
   "description": "Valores da lâtencia do serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_orders_hist_sum{instance=\"orders_service:5600\"}[5m])) / (sum(rate(request_latency_seconds_orders_hist_count{instance=\"orders_service:5600\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de requests",
   "type": "timeseries",
   "description": "Número de requests no serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_count{path=\"/orders\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "increase(flask_http_request_duration_seconds_count{path=\"/orders/fields\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "increase(flask_http_request_duration_seconds_count{path=\"/orders/cancel\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "increase(\n  flask_http_request_duration_seconds_count{\n    path=~\"/orders/.+\",\n    path!=\"/orders/cancel\",\n    path!=\"/orders/fields\",\n    path!=\"/orders/new\"\n  }[$__rate_interval]\n)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Logs do serviço",
   "type": "table",
   "description": "Logs do serviço GW, dos metodos importantes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"orders_service\"} |= `GET` or `POST`"
    }
   ]
  },
  {
   "title": "Erros de metodos",
   "type": "table",
   "description": "Todos os logs de erros ao tentar aceder o nosso serviço.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"orders_service\"} |~ ` 4[0-9][0-9] | 5[0-9][0-9] `"
    }
   ]
  }
 ]
}